export const ActionTypes = {
    FETCH_PRODUCTS:"FETCH_PRODUCTS",
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCTS:"SELECTED_PRODUCTS",
    REMOVE_SELECTED_PRODUCTS:"REMOVE_SELECTED_PRODUCTS",
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    UPDATE_CART_ITEM:'UPDATE_CART_ITEM',
    FETCH_CATEGORIES:'FETCH_CATEGORIES',
    FILTER_CATEGORY:'FILTER_CATEGORY',
    SEARCH_TERM:'SEARCH_TERM',
    SORT_BY:'SORT_BY'
}